title: ArgFuscator
repo: wietze/ArgFuscator.net
baseurl: ''

collections:
  entries:
    output: true
    permalink: /entries/:name

defaults:
  - scope:
      path: "_entries/*"
    values:
      layout: entry
  - scope:
      path: "assets/models"
    values:
      layout: null

include:
  - "assets/models"

mapping:
  Sed:
    name: Character Substitution
    description: Some command-line arguments allow characters to be replaced with Unicode equivalents.
  CharacterInsertion:
    name: Character Insertion
    description: Some command-line arguments allow specific characters to be inserted without altering the meaning of the original command line.
  OptionCharSubstitution:
    name: Option Character Substitution
    description: Command-line option characters, such as those starting with a forward slash or hyphen, have (unicode) alternatives that are also accepted.
  QuoteInsertion:
    name: Quote Insertion
    description: It is possible to add double quotes (in multiples of two) to some of the command-line options. This may obfuscate keywords used on the command line.
  Shorthands:
    name: Shorthands
    description: It is possible to shorten or otherwise abbreviate certain command-line options.
  FilePathTransformer:
    name: File Path Transformations
    description: When file paths are supplied to the executable, it is possible to apply transformations to the file path that may obscure the real path.
  UrlTransformer:
    name: URL Transformations
    description: Any URLs passed on the command line can be transformed in ways that may obscure the true destination.
  RandomCase:
    name: RaNdOmCaSe
    description: Part of the command line is case insensitive, meaning it is possible to use upper- and lowercase characters interchangably. This may frustrate case-sensitive detections.
