name: Deploy to GitHub Pages
on:
 push:
   branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install TypeScript
        run: npm install -g typescript
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true
      - name: Compile TypeScript
        run: |
          mkdir -p gui/assets/js
          tsc --project src/tsconfig.json --outFile gui/assets/js/main.js
          cp -r models gui/assets/models
      - name: Convert JSON configs to YML format
        run: |
          python3 -m pip install pyyaml
          python3 .github/workflows/json-transform.py
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./gui
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
